"""The hosting boundary shared by ingestion, review and knowledge jobs.

The historical MergeRequest model represents a change request on any host.
Adapters return its normalized record shape, not their host's wire payloads:
project: id/path_with_namespace/default_branch; change: iid/sha/state,
diff_refs; diff: old_path/new_path/diff and change flags; discussion: id/notes.
Project and user IDs may be integers or opaque strings (including UUIDs).
Users have id/username/name/bot. Notes have id/provider_note_key/body/author,
created_at/position and explicit reply_to_id where the host provides it.
Original wire data belongs in the `raw` member. Host-specific HTTP, identities,
anchors, refs, pagination and credentials stay inside the adapter.
"""
from dataclasses import dataclass
from typing import Protocol


@dataclass(frozen=True)
class Capabilities:
    resolve_threads: bool = True
    review_versions: bool = True
    selected_requests: bool = False


class GitProvider(Protocol):
    provider_name: str
    capabilities: Capabilities

    def clone_url(self, project_path: str) -> str: ...
    def review_ref(self, number: int) -> str: ...
    async def aclose(self) -> None: ...
    async def get_current_user(self) -> dict: ...
    async def get_project(self, project) -> dict: ...
    async def get_merge_request(self, project, iid) -> dict: ...
    async def list_merge_requests(self, project, updated_after=None, state="all", **kwargs) -> list[dict]: ...
    async def list_discussions(self, project, iid) -> list[dict]: ...
    async def list_notes(self, project, iid) -> list[dict]: ...
    async def list_versions(self, project, iid) -> list[dict]: ...
    async def list_diffs(self, project, iid) -> list[dict]: ...
    async def get_approvals(self, project, iid) -> dict: ...
    async def get_reviewers(self, project, iid) -> list[dict]: ...
    async def get_note_awards(self, project, iid, note_id, *, note_key=None) -> list[dict]: ...
    async def get_branch(self, project, branch: str) -> dict | None: ...
    async def compare(self, project, frm: str, to: str) -> dict: ...
    async def get_file_raw(self, project, path: str, ref: str) -> str: ...
    async def create_discussion(self, project, iid, body: str, position=None) -> dict: ...
    async def create_note(self, project, iid, discussion_id: str, body: str) -> dict: ...
    async def resolve_discussion(self, project, iid, discussion_id: str, resolved: bool) -> dict: ...
