"""baseline

Revision ID: 0c55ad6f57dd
Revises: 
Create Date: 2026-05-03 16:22:47

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = '0c55ad6f57dd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actors',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('provider_user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('is_bot', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id'),
    schema='argus'
    )
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dedup_key', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('locked_by', sa.Text(), nullable=True),
    sa.Column('locked_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('run_after', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('queued','running','done','failed')", name='job_status_check'),
    sa.PrimaryKeyConstraint('id'),
    schema='argus'
    )
    op.create_table('llm_endpoints',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=True),
    sa.Column('api_key_ref', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('tool_calling_native', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.CheckConstraint("provider IN ('anthropic','openai','gemini','ollama','claude_cli_proxy')", name='endpoint_provider_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='argus'
    )
    op.create_table('reviewer_profiles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('current_version_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='argus'
    )
    op.create_table('profile_versions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('guidelines', sa.Text(), nullable=True),
    sa.Column('tool_allowlist', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['argus.reviewer_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'version'),
    schema='argus'
    )
    op.create_foreign_key(
        'reviewer_profiles_current_version_id_fkey', 'reviewer_profiles', 'profile_versions',
        ['current_version_id'], ['id'],
        source_schema='argus', referent_schema='argus')
    op.create_table('repositories',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('project_path', sa.Text(), nullable=False),
    sa.Column('gitlab_project_id', sa.BigInteger(), nullable=False),
    sa.Column('default_branch', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('poll_interval_s', sa.Integer(), nullable=False),
    sa.Column('default_profile_id', sa.UUID(), nullable=True),
    sa.Column('poll_cursor', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['default_profile_id'], ['argus.reviewer_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'project_path'),
    schema='argus'
    )
    op.create_table('merge_requests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('mr_iid', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('merged_by_id', sa.UUID(), nullable=True),
    sa.Column('source_branch', sa.Text(), nullable=False),
    sa.Column('target_branch', sa.Text(), nullable=False),
    sa.Column('head_sha', sa.Text(), nullable=False),
    sa.Column('draft', sa.Boolean(), nullable=False),
    sa.Column('has_conflicts', sa.Boolean(), nullable=False),
    sa.Column('blocking_discussions_resolved', sa.Boolean(), nullable=False),
    sa.Column('detailed_merge_status', sa.Text(), nullable=True),
    sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('web_url', sa.Text(), nullable=False),
    sa.Column('merged_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('closed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('mr_created_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('mr_updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("state IN ('opened','merged','closed','locked')", name='mr_state_check'),
    sa.ForeignKeyConstraint(['author_id'], ['argus.actors.id'], ),
    sa.ForeignKeyConstraint(['merged_by_id'], ['argus.actors.id'], ),
    sa.ForeignKeyConstraint(['repo_id'], ['argus.repositories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_id', 'mr_iid'),
    schema='argus'
    )
    op.create_table('raw_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('mr_iid', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['argus.repositories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='argus'
    )
    op.create_table('discussions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('mr_id', sa.UUID(), nullable=False),
    sa.Column('provider_discussion_id', sa.Text(), nullable=False),
    sa.Column('individual_note', sa.Boolean(), nullable=False),
    sa.Column('resolvable', sa.Boolean(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by_id', sa.UUID(), nullable=True),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mr_id'], ['argus.merge_requests.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['argus.actors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mr_id', 'provider_discussion_id'),
    schema='argus'
    )
    op.create_table('mr_participants',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('mr_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('review_state', sa.Text(), nullable=True),
    sa.Column('approved_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('author','assignee','reviewer','approver','participant')", name='participant_role_check'),
    sa.ForeignKeyConstraint(['actor_id'], ['argus.actors.id'], ),
    sa.ForeignKeyConstraint(['mr_id'], ['argus.merge_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mr_id', 'actor_id', 'role'),
    schema='argus'
    )
    op.create_table('mr_versions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('mr_id', sa.UUID(), nullable=False),
    sa.Column('provider_version_id', sa.BigInteger(), nullable=False),
    sa.Column('head_commit_sha', sa.Text(), nullable=False),
    sa.Column('base_commit_sha', sa.Text(), nullable=False),
    sa.Column('start_commit_sha', sa.Text(), nullable=False),
    sa.Column('version_created_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mr_id'], ['argus.merge_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mr_id', 'provider_version_id'),
    schema='argus'
    )
    op.create_table('notes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('mr_id', sa.UUID(), nullable=False),
    sa.Column('discussion_id', sa.UUID(), nullable=True),
    sa.Column('parent_note_id', sa.UUID(), nullable=True),
    sa.Column('provider_note_id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('author_type', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('system_event_type', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('line', sa.Integer(), nullable=True),
    sa.Column('position', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('suggestions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('disposition', sa.Text(), nullable=False),
    sa.Column('note_created_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("author_type IN ('bot','human','system')", name='note_author_type_check'),
    sa.CheckConstraint("disposition IN ('open','accepted','accepted_manually','answered','rejected_with_rationale','dismissed_ambiguous','resolved_no_answer')", name='note_disposition_check'),
    sa.CheckConstraint("kind IN ('inline','summary','system')", name='note_kind_check'),
    sa.ForeignKeyConstraint(['author_id'], ['argus.actors.id'], ),
    sa.ForeignKeyConstraint(['discussion_id'], ['argus.discussions.id'], ),
    sa.ForeignKeyConstraint(['mr_id'], ['argus.merge_requests.id'], ),
    sa.ForeignKeyConstraint(['parent_note_id'], ['argus.notes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mr_id', 'provider_note_id'),
    schema='argus'
    )
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('mr_id', sa.UUID(), nullable=False),
    sa.Column('mr_version_id', sa.UUID(), nullable=True),
    sa.Column('profile_version_id', sa.UUID(), nullable=True),
    sa.Column('llm_endpoint_id', sa.UUID(), nullable=True),
    sa.Column('trigger', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('llm_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('langfuse_trace_id', sa.Text(), nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('queued','running','done','failed','canceled')", name='review_status_check'),
    sa.ForeignKeyConstraint(['llm_endpoint_id'], ['argus.llm_endpoints.id'], ),
    sa.ForeignKeyConstraint(['mr_id'], ['argus.merge_requests.id'], ),
    sa.ForeignKeyConstraint(['mr_version_id'], ['argus.mr_versions.id'], ),
    sa.ForeignKeyConstraint(['profile_version_id'], ['argus.profile_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='argus'
    )
    op.create_table('feedback',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('note_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('reply','applied','reaction','resolved','ui_answer')", name='feedback_kind_check'),
    sa.ForeignKeyConstraint(['actor_id'], ['argus.actors.id'], ),
    sa.ForeignKeyConstraint(['note_id'], ['argus.notes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='argus'
    )
    op.create_table('file_knowledge',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('blob_sha', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('key_symbols', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('updated_by_review_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['argus.repositories.id'], ),
    sa.ForeignKeyConstraint(['updated_by_review_id'], ['argus.reviews.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_id', 'file_path'),
    schema='argus'
    )
    op.create_table('findings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('line', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('evidence_quote', sa.Text(), nullable=True),
    sa.Column('suggestion_old', sa.Text(), nullable=True),
    sa.Column('suggestion_new', sa.Text(), nullable=True),
    sa.Column('verdict_valid', sa.Boolean(), nullable=True),
    sa.Column('verdict_reason', sa.Text(), nullable=True),
    sa.Column('published_note_id', sa.UUID(), nullable=True),
    sa.Column('provider_suggestion_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("severity IN ('critical','high','medium','low')", name='finding_severity_check'),
    sa.CheckConstraint("type IN ('issue','suggestion')", name='finding_type_check'),
    sa.ForeignKeyConstraint(['published_note_id'], ['argus.notes.id'], ),
    sa.ForeignKeyConstraint(['review_id'], ['argus.reviews.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='argus'
    )
    op.create_table('learnings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=True),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('hint_text', sa.Text(), nullable=False),
    sa.Column('file_pattern', sa.Text(), nullable=True),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('miss_count', sa.Integer(), nullable=False),
    sa.Column('inconclusive_count', sa.Integer(), nullable=False),
    sa.Column('source_review_id', sa.UUID(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active','archived')", name='learning_status_check'),
    sa.ForeignKeyConstraint(['repo_id'], ['argus.repositories.id'], ),
    sa.ForeignKeyConstraint(['source_review_id'], ['argus.reviews.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='argus'
    )
    op.create_table('llm_rounds',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('stage_name', sa.Text(), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['argus.reviews.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='argus'
    )
    op.create_table('review_stages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('stage_name', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('artifact', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('running','done','failed')", name='stage_status_check'),
    sa.ForeignKeyConstraint(['review_id'], ['argus.reviews.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id', 'stage_name'),
    schema='argus'
    )
    op.create_table('tool_calls',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('stage_name', sa.Text(), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.Text(), nullable=False),
    sa.Column('args', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['argus.reviews.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='argus'
    )
    op.create_table('injection_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('learning_id', sa.UUID(), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("outcome IN ('pending','hit','miss','inconclusive')", name='injection_outcome_check'),
    sa.ForeignKeyConstraint(['learning_id'], ['argus.learnings.id'], ),
    sa.ForeignKeyConstraint(['review_id'], ['argus.reviews.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='argus'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('reviewer_profiles_current_version_id_fkey', 'reviewer_profiles',
                       schema='argus', type_='foreignkey')
    op.drop_table('injection_events', schema='argus')
    op.drop_table('tool_calls', schema='argus')
    op.drop_table('review_stages', schema='argus')
    op.drop_table('llm_rounds', schema='argus')
    op.drop_table('learnings', schema='argus')
    op.drop_table('findings', schema='argus')
    op.drop_table('file_knowledge', schema='argus')
    op.drop_table('feedback', schema='argus')
    op.drop_table('reviews', schema='argus')
    op.drop_table('notes', schema='argus')
    op.drop_table('mr_versions', schema='argus')
    op.drop_table('mr_participants', schema='argus')
    op.drop_table('discussions', schema='argus')
    op.drop_table('raw_events', schema='argus')
    op.drop_table('merge_requests', schema='argus')
    op.drop_table('repositories', schema='argus')
    op.drop_table('profile_versions', schema='argus')
    op.drop_table('reviewer_profiles', schema='argus')
    op.drop_table('llm_endpoints', schema='argus')
    op.drop_table('jobs', schema='argus')
    op.drop_table('actors', schema='argus')
    # ### end Alembic commands ###
