"""make mr_versions.base_commit_sha nullable

Revision ID: ca6741ec2511
Revises: 2448bbec2581
Create Date: 2026-07-03 21:25:59.461810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca6741ec2511'
down_revision: Union[str, Sequence[str], None] = '2448bbec2581'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mr_versions', 'base_commit_sha',
               existing_type=sa.TEXT(),
               nullable=True,
               schema='argus')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mr_versions', 'base_commit_sha',
               existing_type=sa.TEXT(),
               nullable=False,
               schema='argus')
    # ### end Alembic commands ###
