"""reviewer proxies

Revision ID: e6e468d5bd81
Revises: c1c897cb7d36
Create Date: 2026-05-23 14:38:21

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6e468d5bd81'
down_revision: Union[str, Sequence[str], None] = 'c1c897cb7d36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate also proposed dropping unrelated `checkpoint_*`
    # tables (leftovers from another tool sharing this dev database, not
    # part of the argus SQLAlchemy models); those were stripped from
    # this migration as out of scope for this task.
    op.create_table('reviewer_proxies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('reviewer', sa.Text(), nullable=False),
    sa.Column('proxy_url', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reviewer'),
    schema='argus'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviewer_proxies', schema='argus')
    # ### end Alembic commands ###
