"""make mr_versions.base_commit_sha nullable

Revision ID: ed742e4d572a
Revises: 0c55ad6f57dd
Create Date: 2026-05-09 14:27:38

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed742e4d572a'
down_revision: Union[str, Sequence[str], None] = '0c55ad6f57dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mr_versions', 'base_commit_sha',
               existing_type=sa.TEXT(),
               nullable=True,
               schema='argus')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mr_versions', 'base_commit_sha',
               existing_type=sa.TEXT(),
               nullable=False,
               schema='argus')
    # ### end Alembic commands ###
